Sample/Models/ErrorViewModel.cs
using System;

namespace Sample.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sample/Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace Sample.Models
{
    public class UserInfo
    {
        public int Id { get; set; }

        //[Required(AllowEmptyStrings = false, ErrorMessage = "Name property required")]
        public string Name { get; set; }

        public int Age { get; set; }
    }
}

Sample/Controllers/DoStuffController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System;

namespace Sample.Controllers
{
    public class DoStuffController : Controller
    {
        private ILogger<DoStuffController> _logger;


        public DoStuffController(ILogger<DoStuffController> logger)
        {
            _logger = logger;
        }


        [HttpGet]
        public IActionResult Index(string? stuff)
        {
            var some = stuff;

            return View();
        }

        [HttpPost]
        public IActionResult Index(int? number)
        {
            _logger.LogInformation("Begin post Index method execution");

            if (number == null)
            {
                _logger.LogWarning("Expected argument number");
            }
            else
            {
                DoStuffWithNumber(number.Value);
            }

            return RedirectToAction(nameof(Index));
        }


        private void DoStuffWithNumber(int number)
        {
            _logger.LogInformation("Begin DoStuffWithNumber method execution");
            _logger.LogInformation("Got number={number}", number);

            if (number < 0)
            {
                _logger.LogError("number should be greater than zero");

                throw new ArgumentException("number should be greater than zero", nameof(number));
            }
            if(number > 1000)
            {
                _logger.LogWarning("number is too large, can cause some calculation issues");
            }


            var rand = new Random();
            var multiplier = rand.Next(100);

            var thirdPartyArgument = rand.Next(100);

            if(thirdPartyArgument > 40 && thirdPartyArgument < 70)
            {
                _logger.LogWarning("Third-party took too long to respond, greater response time can cause an error. Current response time = {0}ms", thirdPartyArgument);
            }
            else if(thirdPartyArgument > 70)
            {
                _logger.LogError("Shutting down third-party call due to long response time. Current response time={0}ms", thirdPartyArgument);

                throw new TimeoutException("Third-party took too long to respond");
            }

            _logger.LogInformation("Retrieved argument from third-party={0}", thirdPartyArgument);
            _logger.LogTrace("First multiplier={0}", multiplier);

            var newNumber = number * rand.Next(100);

            _logger.LogInformation("New number={0}", newNumber);

            var oldPlusNew = newNumber + number;

            _logger.LogDebug("Old + new={0}", oldPlusNew);

            var work = Math.Log10(Math.Round(newNumber * Math.PI + Math.Pow(oldPlusNew, 3))) + thirdPartyArgument;

            _logger.LogInformation("End of DoStuffWithNumber method execution, Result={0}", work);
        }
    }
}

Sample/Controllers/DonationsController.cs
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Sample.DataAccess;

namespace Sample.Controllers
{
    [AuditPolicy(false)]
    public class DonationsController : Controller
    {
        private ApplicationContext _context;
        private ILogger<DonationsController> _logger;

        public DonationsController(ApplicationContext context, ILogger<DonationsController> logger)
        {
            _context = context;
            _logger = logger;
        }


        public ActionResult Index()
        {
            _logger.LogTrace("Begin retrieving Donations");

            var donations = _context.Donations.ToList();

            _logger.LogDebug("Retrieved {amount} donations", donations.Count);

            return View(donations);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var donation = await _context.Donations.FindAsync(id);

            if(donation == null)
            {
                _logger.LogWarning("Donation with id={donationId} not found", id);
            }
            else
            {
                _logger.LogTrace("Deleting donation id={donationId}", id);
                _context.Donations.Remove(donation);

                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Sample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Sample.DataAccess;
using Sample.DataAccess.Models;
using System;

namespace Sample.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(int? id)
        {
            return View();
        }

        public IActionResult Error()
        {
            throw new NotImplementedException();

            return View();
        }

        [HttpGet]
        public IActionResult Donate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Donate(Donation donation)
        {
            _context.Donations.Add(donation);
            _context.SaveChanges();

            return View();
        }
    }
}

Sample/Controllers/ModelsController.cs
using Microsoft.AspNetCore.Mvc;
using Sample.Models;

namespace Sample.Controllers
{
    public class ModelsController : Controller
    {
        [BindProperty(SupportsGet = true)]
        public UserInfo UserInfo { get; set; }

        [BindProperty(Name = "Info", SupportsGet = true)]
        public string SomeInfo { get; set; }

        public string SomeOtherInfo { get; set; }


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetInfo()
        {
            var responce = $"{UserInfo?.Name}, {UserInfo?.Age}. {nameof(SomeInfo)} = {SomeInfo}, {nameof(SomeOtherInfo)} = {SomeOtherInfo}";

            return new OkObjectResult(responce);
        }


        [HttpPost]
        public IActionResult ProcessInfo(UserInfo info)
        {
            if(!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            return new OkObjectResult(info);
        }

        [HttpPost]
        [Consumes("application/json")]
        public IActionResult ProcessInfo2([FromBody] UserInfo info)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            return new OkObjectResult(info);
        }
    }
}

Sample/Views/DoStuff/Index.cshtml
<div>
    <h3>Enter number to process</h3>
    <form method="post">
        <table>
            <tr>
                <td>Number:</td>
                <td><input type="number" name="Number" /> </td>
            </tr>
            <tr><td><input type="submit" value="Sumbit" /> </td><td></td></tr>
        </table>
    </form>
</div>

Sample/Views/Donations/Index.cshtml
@model IEnumerable<Sample.DataAccess.Models.Donation>

@{
    ViewData["Title"] = "Donations";
}

<h1>Donations</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Sample/Views/Home/Donate.cshtml
@{
    ViewData["Title"] = "Donate Us";
}

<div>
    <h3>Donate us</h3>
    <form method="post">
        <input type="hidden" value="@ViewBag.Id" name="Id" />
        <table>
            <tr>
                <td>Email:</td>
                <td><input type="email" name="Email" /> </td>
            </tr>
            <tr>
                <td>Name:</td>
                <td><input type="text" name="Name" /></td>
            </tr>
            <tr>
                <td>Amount:</td>
                <td><input type="number" name="Amount" /></td>
            </tr>
            <tr><td><input type="submit" value="Sumbit" /> </td><td></td></tr>
        </table>
    </form>
</div>

Sample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Sample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sample</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Donate">Donate Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Donations" asp-action="Index">View Donations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DoStuff" asp-action="Index">Do stuff</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Sample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>